### ISSUE TITLE
Invalid provider preset/location: "infuraGoerli"

### ISSUE THREAD

**Issue by Feelthewind** [floating/eth-provider#40] opened 2021-04-27 12:32 UTC
Hi, author. Thank you for this awesome library.

I have a problem connecting to infura goerli network using preset. 
Error message => eth-provider | Invalid provider preset/location: "infuraGoerli"

```
const ethProvider = require('eth-provider');

const target = 'infuraGoerli'

this.provider = ethProvider(target, {
  infuraId: 'my infura id',
});

this.provider.send(
  'eth_chainId'
).then(console.log);
```

Kovan and other test networks are working ok.

**Comment by floating** [comment] 2021-04-29 20:53
Hey @Feelthewind sorry for the delay, are you still experiencing this issue?

I ran your example and was unable to reproduce the error

**Comment by floating** [comment] 2021-05-12 22:59
Closing for now, if you can reproduce this error please reach out again so we can help!

**Closed by floating** 2021-05-12 22:59 UTC
